id: P58171A24
initial_creation_type: ocr
source_metadata:
  volumes:
    3c9f6fdb04ca421a92f175a2996932e2:
      base_file: v053.txt
      image_group_id: I1PD95898
      title: ཤེས་རབས་ཀྱི་ཕ་རོལ་ཏུ་ཕྱིན་པའི་དོན་བསྡུས་སྒྲོན་མ།
      total_pages: 1381
      volume_number: 53
